export const TENSION_DECK = {
  GreenCard: 'Green Card',
  EchoesInTheDarkness: 'Echoes in the Darkness',
  NoEscape: 'No Escape...',
  PrehensileGrasp: 'Prehensile Grasp',
  UndeadAmbush: 'Undead Ambush',
  BloodcurdlingHowl: 'Bloodcurdling Howl',
  PersistingUnease: 'Persisting Unease',
  MurderOfCrows: 'Murder of Crows',
  ToughHide: 'Tough Hide',
  HideousScreech: 'Hideous Screech',
  VigourMortis: 'Vigour Mortis',
  RisingFear: 'Rising Fear',
  CrimsonThirst: 'Crimson Thirst',
};
